---
# file: tasks/main.yml -- main tasks file

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version|lower}}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower}}.yml"
    - "{{ ansible_distribution|lower }}.yml"
  become: true
  tags: vars
