# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: 23.10.1
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-builtins, pep8-naming, flake8-fixme, flake8-bugbear, flake8-import-order]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint
  - repo: local
    hooks:
      - id: pylint-errors
        name: Check pylint errors
        entry: pylint -E
        language: system
        types: [python]
        require_serial: true
      - id: poetry-check
        name: Validate pyproject.toml
        entry: poetry check
        language: system
        types: [file]
        files: "^pyproject.toml$"
        pass_filenames: false
