all:
  hosts:
    ovh-debian-host:
      ansible_connection: 'ssh'
      ansible_user: 'debian'
    children:
      production:
        hosts:
          ovh-debian-host:
      ovh-vps:
        hosts:
          ovh-debian-host:
